version: "2.1"

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
      - "1099:1099"
    links:
      - zookeeper:zk
    depends_on:
      - metrics
      - zookeeper
    environment:
      HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_ZOOKEEPER_CONNECT: "zk:2181"
      KAFKA_CREATE_TOPICS: "Words:2:1,Points:2:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # Dirty ass hack to make sure word-producer doesn't start until kafka is "ready"
    healthcheck:
      test: ["CMD", "grep", "No checkpointed highwatermark is found for partition Points-1", "/opt/kafka/logs/server.log"]
      interval: 1s
      retries: 60

  kafkamanager:
    image: sheepkiller/kafka-manager
    ports:
      - "9000:9000"
    environment:
      APPLICATION_SECRET: "letmein"
      ZK_HOSTS: "zk:2181"
      JMX_PORT: 1099
    links:
      - zookeeper:zk
    depends_on:
      - kafka
      - zookeeper

  metrics:
    image: kamon/grafana_graphite
    ports:
      - "80:80"

  word-producer:
    build: word-producer
    ports:
      - "9091:9091"
    environment:
      LOGGING: "DEBUG"
    depends_on:
      kafka:
        condition: service_healthy

  word-consumer:
    build: word-consumer
    environment:
      LOGGING: "DEBUG"
    depends_on:
      kafka:
        condition: service_healthy

  points-consumer:
    build: points-consumer
    ports:
      - "9090:9091"
    environment:
      LOGGING: "DEBUG"
    depends_on:
      kafka:
        condition: service_healthy

  points-spender:
    build: points-spender
    environment:
      LOGGING: "DEBUG"
    depends_on:
      kafka:
        condition: service_healthy
